### PR TITLE
Update the Obj-C generator to have generated protocols conform to NSObject

### PR DESCRIPTION
**Pull request by ngmeyer**
All Obj-C protocols will now conform to NSObject.

### CODE REVIEW

**Comment by ngmeyer** [comment]
fixes #117

**Comment by a4z** [comment]
This is the forward declaration, so that should be fine as it is
https://github.com/cross-language-cpp/djinni-generator/blob/09b420537183e0f941ae55afbf15d72c3f8b76a1/src/main/scala/djinni/ObjcppGenerator.scala#L147

but I  have a hard time remembering what that does
https://github.com/cross-language-cpp/djinni-generator/blob/09b420537183e0f941ae55afbf15d72c3f8b76a1/src/main/scala/djinni/ObjcMarshal.scala#L78
if this is triggered by some tests (not sure (note to myself, add code coverage)) and if that can stay as it is or not.
Any insights on that, @artwyman , do you maybe remember if that is covered by some test?

**Comment by freitass** [comment]
> ...
> but I have a hard time remembering what that does
> 
> https://github.com/cross-language-cpp/djinni-generator/blob/09b420537183e0f941ae55afbf15d72c3f8b76a1/src/main/scala/djinni/ObjcMarshal.scala#L78
> 
> 
> if this is triggered by some tests (not sure (note to myself, add code coverage)) and if that can stay as it is or not.
> Any insights on that, @artwyman , do you maybe remember if that is covered by some test?

Here's a small example that triggers that line:
```djinni
custom_interface = interface +o {
  test();
}

other_interface = interface +o {
  custom(): custom_interface;
}
```

which results in:

```objc
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#import <Foundation/Foundation.h>
@protocol ITCustomInterface;


@protocol ITOtherInterface

- (nullable id<ITCustomInterface>)custom;

@end
```

To be honest, I don't know if it needs to be changed for the scope of this PR.

**Comment by artwyman** [comment]
I'm too rusty on ObjC to know whether forward declarations of protocols should declare their inheritance relationship, or if that could cause multiple-definition errors.  I'd guess that any code which actually tries call methods on an interface object will want to include its full definition anyway, so the point may be moot.  There could be cases where there would be a difference, though.

If you wanted to test this to see what works better, I'd suggest creating a test case corresponding to the use case which motivated this PR.  I.e. write some code which calls [object class] on an object using a Djinni protocol type.  Then see if you can do it successfully with only a forward-decl or if it requires the full definition of the protocol.  Then see if adding the protocol inheritance to the forward-decl changes the behavior.

**Comment by a4z** [comment]
Thanks all together, seems that is indeed all it needs.

Yes, we need more testing, also code that is not just checked against other code, but actually executed.
We are working on that, but that takes time ... 

I think we pull it in, and in case something is missing, some one will tell us anyway ...

**Review by a4z — APPROVED** [review]

**Review by jothepro — APPROVED** [review]
From what I've read in Slack this change seems to have no known side effects. I'm fine with it 👍

**Comment by eakoli** [comment]
@a4z This change forces all swift objects that implement a protocol to be derived from NSObject, instead if just being able to implement the protocol.

**Comment by a4z** [comment]
Hi @eakoli , can you please provide an example that highlights the problem. And, it you think this is a problem, open a ticket so this can be discussed more publicly. Here, at a closed PR it will not be very visible. Thanks!

**Pull request merged**
