### PR TITLE
[Draft] External symbol support for c wrapper 

### PR DESCRIPTION
**Pull request by gibutm**
Raising a draft PR for review and suggestions.

### CODE REVIEW

**Comment by a4z** [comment]
Thanks a lot @gibutm !

I guess this PR targets #140 ?

Since you commit the first time, the CI does not auto-trigger for your commit.
This is a security feature of github. 
I run it now, and it reports some formatting issues.

Please see [code-formatting documentation](https://djinni.xlcpp.dev/djinni-generator/developer-guide/#code-formatting) for more information.

Not sure if CI will auto-trigger after your next commit, or if I have to do it manually again, will see.

**Comment by gibutm** [comment]
Thanks for triggering the CI checks, this PR targets #139. 
I may need some help in understanding how the python layer interacts with the C wrapper before i can give #140 a crack. 

I will correct the formatting and update the PR in the meanwhile.

**Comment by freitass** [comment]
Hi @gibutm! I'm curious about your use case. Do you use the C wrapper without Python?

Would it be possible to add some tests for the scenario you're covering?

Thank you!

**Comment by a4z** [comment]
Hi @gibutm , please check https://github.com/gibutm/djinni-generator/pull/1
If you merge this, this PR should become green.
Or are you not interested in that feature anymore?

**Pull request closed without merging**
