### PR TITLE
feat(deprecated): generate language specific deprecation markup

### PR DESCRIPTION
**Pull request by eakoli**
If @deprecated is present in a comment, a deprecation marker will be generated.

@deprecated is expected to be at the start of a line, any text following it on the same line is added as the ‘message’ text where supported

This applies to records/attributes/constants, interfaces/methods/constants, enums/values, flags/values

Supports C++, Java and ObjC generators

### CODE REVIEW

**Comment by a4z** [comment]
Wow, this is nice! Thank you so much!!

**Review by a4z — APPROVED** [review]
Great PR! 
We need to add this to the documentation.
But that can happen once it's merged.

**Comment by jothepro** [comment]
Could be nice if this would also support setting the `ObsoleteAttribute` in C++/CLI! @eakoli would you be interested in adding it in this PR or should I open a separate issue for it?

**Review by jothepro — APPROVED** [review]
apart from that it's looking great, thank you so much!

**Comment by a4z** [comment]
If no other comments are made, I will soon merge this PR, and we will handle eventual ideas and additions, like docs, as extra issues.

**Comment by a4z** [comment]
Thanks a lot!
This requires a new release, which will follow soon

**Pull request merged**
