### PR TITLE
Generate full path to support lib include files

### PR DESCRIPTION
**Pull request by a4z**
This targets #14 ,
generated files now include the full path to files includede from
the support lib.

This shall simplify the include setup
Incldue support-lib install_prefix/include is now enough.

This change should not break any existing setups that inlcude full
paths.
However, to restore the previous behavious,
set `--jni-base-lib-include-prefix` to an emppty string

### CODE REVIEW

**Comment by a4z** [comment]
If there are no different opinions that this is a bad idea, I will start adoption the tests so they reflect the new reality

**Comment by a4z** [comment]
Did some additional testing, I think it is safe to apply the change.

We will need to have to add an additional documentation issue for the next release where this changes is described, 
but since this will contain more than just this pr, I would like having that in an extra PR

**Review by jothepro — CHANGES_REQUESTED** [review]
Please document the default values in `--help` + the [documentation](https://djinni.xlcpp.dev/djinni-generator/cli-usage/)

**Comment by a4z** [comment]
I was actually planning to do the docs in the context of #23

**Comment by jothepro** [comment]
hm. I'm not sure if were talking about the same kind of documentation.
Documenting the default value in the `--help` command requires a code change [here](https://github.com/a4z/djinni-generator/blob/include-prefix/src/main/scala/djinni/Main.scala#L162), I see this change in the scope of this PR. What I mean: 
```
> djinni --help
...
--jni-include-prefix <prefix>   The prefix for #includes of JNI header files from JNI C++ files (default: djinni/jni/).
```

This is how default values are documented for all other properties.

The docs contain just a copy of the --help output, so [here](https://github.com/a4z/djinni-generator/blob/include-prefix/docs/cli-usage.md#jni) the same change is required.

**Comment by a4z** [comment]
ah, ok, awesome catch!!

its those section that have the doc for this change
```
      opt[String]("jni-base-lib-include-prefix").valueName("...").foreach(x => jniBaseLibIncludePrefix = x)
        .text("The JNI base library's include path, relative to the JNI C++ classes.")
```
and
```
      opt[String]("objc-base-lib-include-prefix").valueName("...").foreach(x => objcBaseLibIncludePrefix = x)
        .text("The Objective-C++ base library's include path, relative to the Objective-C++ classes.")
```

any suggestion for the text?

What about
`The djinni-support-lib JNI include path. Deprecated, only available for backward compatibility.`
and
`The djinni-support-lib Objective-C include path. Deprecated, only available for backward compatibility.`
for both ?

**Comment by jothepro** [comment]
I don't understand the purpose of this parameter. :/

**Comment by jothepro** [comment]
Silly me, it's the params that you have set default values for 🙈 .
I don't see them as deprecated, it's just that they have a useful default value already set. 🤔

**Comment by a4z** [comment]
they are deprecated, except for code that is generated with old generator version, where you need to set it to ""

**Comment by jothepro** [comment]
What if someone decided to not install the base lib as it is, but copy it's files to a different folder structure? 🤔 
What I want to say: to me it seems like these parameters allow you to configure something that normally you do not want to configure. But in my opinion that does not make them deprecated, it just makes them not very interesting. The fact that you have decided to set a new default value for them is a proof to me that they are not useless :P
Deprecating them would mean that we discourage users from using these parameters because they may be removed in the future. I don't think that this is the case, or is it?

**Comment by a4z** [comment]
you describe what I say with `except in serious exotic setups I do not want to think about.` :-) 
No plans for removal of that option.

So simply update the text to 
`The djinni-support-lib Objective-C include path.`
and add some hint on the website docs that you do not want to use it ?

**Comment by jothepro** [comment]
What I'd put there: 

    The JNI base library's include path (default: djinni/jni/).

I prefer this because it follows the same pattern as the other parameters documentation.
I think it is important to have the default value documented. I'd prefer not to have a link or any deeper explanation in there because it would clutter the cli output.

But I think I'm starting to see why you want to add a "deprecated" or "do not use" hint. It's not user friendly to have the configuration parameters list bloated with options that basically nobody needs to set... I'm not sure what to think about this right now. This may apply to a lot of options.

**Comment by a4z** [comment]
sounds good, thanks!
Will fix it tomorrow

**Review by jothepro — APPROVED** [review]
Awesome!

**Pull request merged**
